# Generated by Django 5.1.7 on 2025-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_alter_sheikhprofile_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'Male'), ('أنثى', 'Female')], max_length=10, null=True),
        ),
    ]
