# Generated by Django 5.1.7 on 2025-03-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationcode_delete_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
    ]
