# Generated by Django 5.1.7 on 2025-05-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sheikhverification_certificateimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheikhverification',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='sheikhverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='CertificateImage',
        ),
        migrations.DeleteModel(
            name='SheikhVerification',
        ),
    ]
