# Generated by Django 5.1.7 on 2025-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('religious', 'Religious Knowledge'), ('practice', 'Daily Practice'), ('lifestyle', 'Community & Lifestyle'), ('contemporary', 'Contemporary Issues'), ('community', 'Community Engagement'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of this tag topic', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name_ar',
            field=models.CharField(blank=True, help_text='Arabic display name for the tag', max_length=100, null=True),
        ),
    ]
