# Generated by Django 5.1.7 on 2025-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('religious', 'Religious Knowledge'), ('practice', 'Daily Practice'), ('lifestyle', 'Community & Lifestyle'), ('contemporary', 'Contemporary Issues'), ('community', 'Community Engagement'), ('suggestions', 'suggested'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
