# Generated by Django 5.1.7 on 2025-05-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_fix_remaining_cascade_deletes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    ("religious", "Religious Knowledge"),
                    ("practice", "Daily Practice"),
                    ("lifestyle", "Community & Lifestyle"),
                    ("contemporary", "Contemporary Issues"),
                    ("community", "Community Engagement"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
